package com.autobid.model;

import java.util.Date;

public class BidList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.listing_id
     *
     * @mbggenerated
     */
    private Integer listingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.months
     *
     * @mbggenerated
     */
    private Integer months;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.rate
     *
     * @mbggenerated
     */
    private Integer rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.bid_amount
     *
     * @mbggenerated
     */
    private Integer bidAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bid_list.log_time
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.id
     *
     * @return the value of bid_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.id
     *
     * @param id the value for bid_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.title
     *
     * @return the value of bid_list.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.title
     *
     * @param title the value for bid_list.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.listing_id
     *
     * @return the value of bid_list.listing_id
     *
     * @mbggenerated
     */
    public Integer getListingId() {
        return listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.listing_id
     *
     * @param listingId the value for bid_list.listing_id
     *
     * @mbggenerated
     */
    public void setListingId(Integer listingId) {
        this.listingId = listingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.months
     *
     * @return the value of bid_list.months
     *
     * @mbggenerated
     */
    public Integer getMonths() {
        return months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.months
     *
     * @param months the value for bid_list.months
     *
     * @mbggenerated
     */
    public void setMonths(Integer months) {
        this.months = months;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.rate
     *
     * @return the value of bid_list.rate
     *
     * @mbggenerated
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.rate
     *
     * @param rate the value for bid_list.rate
     *
     * @mbggenerated
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.amount
     *
     * @return the value of bid_list.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.amount
     *
     * @param amount the value for bid_list.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.bid_amount
     *
     * @return the value of bid_list.bid_amount
     *
     * @mbggenerated
     */
    public Integer getBidAmount() {
        return bidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.bid_amount
     *
     * @param bidAmount the value for bid_list.bid_amount
     *
     * @mbggenerated
     */
    public void setBidAmount(Integer bidAmount) {
        this.bidAmount = bidAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bid_list.log_time
     *
     * @return the value of bid_list.log_time
     *
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bid_list.log_time
     *
     * @param logTime the value for bid_list.log_time
     *
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
}